# -*- coding: utf-8 -*-
"""
train_sam3.py  —  Finetune SAM 3 on TOAD histology segmentation

Strategy
--------
- Use build_sam3_image_model(eval_mode=False) — the full image model with Hungarian matcher.
- Freeze the ViT backbone (32-layer, 1024-dim) to keep GPU memory and wall-time manageable.
- Finetune: geometry encoder, transformer encoder+decoder, segmentation head.
- One image per step (batch_size=1); all tissue classes in that image are prompted together.
- Loss: Dice + BCE on matched (pred, GT) mask pairs, computed directly from model output.
- Box prompts come from the SEKO-predicted mask (not GT) — see ToadSam3Dataset —
  so training sees the same (imperfect) prompt distribution as inference on
  images with no ground truth. GT still supplies the loss/DICE target.
- SEKO's checkpoint was retrained with osteophyte pixels merged into cartilage,
  so it only ever outputs 5 classes (background + 4 tissue types). GT masks are
  remapped the same way (osteophyte label 5 -> cartilage label 2) before use,
  so the loss target stays consistent with what SEKO can actually prompt for.
  Osteophyte is intentionally not tracked as its own class right now.

Inputs (from train_seko.csv, generated by src/utils/cache_seko_masks.py)
--------------------------------------------------------------------------
  image_path     : RGB .tif, any size  → resized to 1008×1008
  mask_path      : uint8 .tif, values 0-5 (TOAD label schema) — GT; label 5
                    (osteophyte) is remapped to 2 (cartilage) on load
  seko_mask_path : uint8 .tif, values 0-4 — SEKO prediction, used as box-prompt source
  stain          : HE | SafO | TolBlu  (unused during training, kept for stratified splits)

Usage
-----
  conda activate seko-sam3
  python src/utils/cache_seko_masks.py   # once, to populate train_seko.csv
  python src/train_sam3.py
  python src/train_sam3.py --ckpt models/sam3_checkpoint.pt --epochs 30 --lr 1e-4
"""

import argparse
import contextlib
import json
import os
import time

from scipy.optimize import linear_sum_assignment

import cv2
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
import yaml
from PIL import Image
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
from torchvision import tv_tensors
from torchvision.transforms import v2

from sam3 import build_sam3_image_model
from sam3.model.data_misc import BatchedFindTarget, FindStage
from sam3.model.geometry_encoders import Prompt
from sam3.train.loss.loss_fns import dice_loss

CONFIG_PATH = os.path.join(os.path.dirname(__file__), "..", "configs", "baseline.yml")

# ── Constants ──────────────────────────────────────────────────────────────
"""
Need to play around with some of these numbers.
MIN_MASK_AREA_PX is a heuristic to filter out tiny tissue classes that are likely noise.
Need to figure out the proper value.
"""
SAM3_RESOLUTION  = 1008      # ViT input size
SAM3_IMAGE_MEAN  = [0.5, 0.5, 0.5]
SAM3_IMAGE_STD   = [0.5, 0.5, 0.5]
MIN_MASK_AREA_PX = 50        # ignore tissue classes with < 50 px in mask

# SEKO's current checkpoint was retrained with osteophyte merged into
# cartilage — it has 5 output classes total (background + these 4), not 6.
# Osteophyte (raw GT label 5) is intentionally not tracked as its own class
# right now; GT_OSTEOPHYTE_LABEL pixels get remapped into cartilage on load
# (see _merge_osteophyte_into_cartilage) so the loss target matches what
# SEKO can actually prompt for.
TISSUE_LABELS         = [1, 2, 3, 4]  # bone, cartilage, gp, marrow
TISSUE_NAMES          = {1: "Bone", 2: "Cartilage", 3: "Growth Plate", 4: "Marrow"}
GT_OSTEOPHYTE_LABEL   = 5
GT_OSTEOPHYTE_MERGE_INTO = 2  # cartilage


# ── Preprocessing / data augmentation ────────────────────────────────────
# Deterministic preprocessing — no randomness. Used for validation, and
# imported by eval_sam3.py for inference.
_transform = v2.Compose([
    v2.ToDtype(torch.uint8, scale=True),
    v2.Resize((SAM3_RESOLUTION, SAM3_RESOLUTION)),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=SAM3_IMAGE_MEAN, std=SAM3_IMAGE_STD),
])

# Geometric augmentation — applied jointly to image + mask via torchvision's
# v2 API (both passed in the same call) so they receive identical random
# flip/rotation parameters and stay pixel-aligned. v2 uses nearest-neighbor
# interpolation for tv_tensors.Mask automatically, regardless of the image's
# interpolation, so label values are never blurred.
_geometric_augmentation = v2.Compose([
    v2.RandomHorizontalFlip(p=0.5),
    v2.RandomVerticalFlip(p=0.5),
    v2.RandomRotation(degrees=20),
])

# Photometric augmentation — image only. Never applied to the label mask.
_photometric_augmentation = v2.ColorJitter(
    brightness=0.2, contrast=0.2, saturation=0.2, hue=0.05
)


def preprocess_image(image_rgb: np.ndarray) -> torch.Tensor:
    """Deterministic preprocessing, no augmentation: (H, W, 3) uint8 → (1, 3, 1008, 1008) float32."""
    t = torch.from_numpy(image_rgb).permute(2, 0, 1)  # (3, H, W)
    return _transform(t).unsqueeze(0)


def augment_triplet(
    image_rgb: np.ndarray, gt_mask: np.ndarray, seko_mask: np.ndarray,
) -> tuple[torch.Tensor, np.ndarray, np.ndarray]:
    """
    Apply geometric augmentation jointly to image + GT mask + SEKO mask
    (keeping all three pixel-aligned), then photometric augmentation to
    the image only.

    Returns (image_tensor (1, 3, 1008, 1008) float32, gt_mask (H, W) uint8,
    seko_mask (H, W) uint8) — masks geometrically transformed the same way
    as the image, still at the original H, W resolution so box/mask
    extraction works unchanged.
    """
    img_t  = torch.from_numpy(image_rgb).permute(2, 0, 1)          # (3, H, W) uint8
    gt_t   = tv_tensors.Mask(torch.from_numpy(gt_mask)[None])      # (1, H, W) uint8
    seko_t = tv_tensors.Mask(torch.from_numpy(seko_mask)[None])    # (1, H, W) uint8

    img_t, gt_t, seko_t = _geometric_augmentation(img_t, gt_t, seko_t)
    img_t = _photometric_augmentation(img_t)

    return _transform(img_t).unsqueeze(0), gt_t[0].numpy(), seko_t[0].numpy()

# ── Dataset ────────────────────────────────────────────────────────────────

def _merge_osteophyte_into_cartilage(gt_mask: np.ndarray) -> np.ndarray:
    """
    Remap raw GT osteophyte pixels (label 5) into cartilage (label 2), so
    the loss target matches SEKO's merged 5-class schema. See TISSUE_LABELS.
    """
    if not np.any(gt_mask == GT_OSTEOPHYTE_LABEL):
        return gt_mask
    gt_mask = gt_mask.copy()
    gt_mask[gt_mask == GT_OSTEOPHYTE_LABEL] = GT_OSTEOPHYTE_MERGE_INTO
    return gt_mask


def _extract_prompted_instances(seko_mask: np.ndarray, gt_mask: np.ndarray):
    """
    Box prompts come from the SEKO-predicted mask; target binary masks
    (for loss/DICE) come from the GT mask, for the same set of classes
    SEKO detected. A class SEKO doesn't detect gets no box and is simply
    absent from this image's instances. gt_mask is expected to already
    have osteophyte merged into cartilage (see _merge_osteophyte_into_cartilage).
    """
    H, W = seko_mask.shape
    boxes_list, masks_list, labels_list = [], [], []
    for label_id in TISSUE_LABELS:
        prompt_binary = (seko_mask == label_id)
        if prompt_binary.sum() < MIN_MASK_AREA_PX:
            continue

        rows = np.any(prompt_binary, axis=1)
        cols = np.any(prompt_binary, axis=0)
        y1, y2 = np.where(rows)[0][[0, -1]]   # inclusive first/last True index
        x1, x2 = np.where(cols)[0][[0, -1]]

        # Normalize to [0, 1] in cxcywh format. +1 because x1/x2 (and y1/y2)
        # are inclusive pixel indices, so the region is (x2 - x1 + 1) px wide.
        cx = (x1 + x2) / 2.0 / W
        cy = (y1 + y2) / 2.0 / H
        bw = (x2 - x1 + 1) / W
        bh = (y2 - y1 + 1) / H

        boxes_list.append([cx, cy, bw, bh])
        masks_list.append(gt_mask == label_id)
        labels_list.append(label_id)
    return boxes_list, masks_list, labels_list


class ToadSam3Dataset(Dataset):
    """
    Loads image / GT-mask / SEKO-predicted-mask triples from train_seko.csv
    (see src/utils/cache_seko_masks.py).

    Box prompts come from the SEKO-predicted mask, not GT — this matches
    what's available at inference time on images with no GT, so SAM 3 is
    trained (and validated) on the same prompt distribution it'll see
    later. The GT mask still supplies the segmentation target for the loss
    and DICE.

    With augment=True (training), image + GT mask + SEKO mask are
    geometrically augmented together (so all three stay pixel-aligned)
    before boxes/masks are extracted, plus photometric augmentation on the
    image only. With augment=False (validation), preprocessing is fully
    deterministic — but prompts still come from SEKO, matching inference.

    __getitem__ returns a dict:
        image_rgb    : (H, W, 3) uint8  — original, un-augmented image (display only)
        image_tensor : (1, 3, 1008, 1008) float32  — model input
        boxes_cxcywh : (N, 4) float32  — SEKO-derived boxes, normalized cxcywh [0, 1]
        binary_masks : (N, H_orig, W_orig) bool — GT per-class binary masks (loss target)
        label_ids    : (N,) long — tissue class IDs (1-4; see TISSUE_LABELS)
    N is the number of tissue classes SEKO detected in this image (≥1).

    Images SEKO detects nothing in are dropped at construction time (not
    per-__getitem__), so every returned sample has ≥1 real instance — no
    fabricated full-image labels.
    """

    def __init__(self, records: list[dict], img_height: int = 192,
                img_width: int = 256, augment: bool = False):
        self.img_height = img_height
        self.img_width  = img_width
        self.augment    = augment

        kept, skipped = [], 0
        for rec in records:
            seko_mask = np.array(Image.open(rec["seko_mask_path"])).astype(np.uint8)
            if seko_mask.shape[:2] != (img_height, img_width):
                seko_mask = cv2.resize(
                    seko_mask, (img_width, img_height), interpolation=cv2.INTER_NEAREST
                )
            if any((seko_mask == label_id).sum() >= MIN_MASK_AREA_PX for label_id in TISSUE_LABELS):
                kept.append(rec)
            else:
                skipped += 1
        if skipped:
            print(f"ToadSam3Dataset: skipped {skipped}/{len(records)} images "
                  f"where SEKO detected no tissue class ≥ {MIN_MASK_AREA_PX}px")
        self.records = kept

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx):
        rec = self.records[idx]

        # ── Load image ──────────────────────────────────────────────────
        img_bgr = cv2.imread(rec["image_path"], cv2.IMREAD_COLOR)
        if img_bgr is None:
            raise IOError(f"Cannot read image: {rec['image_path']}")
        if img_bgr.shape[:2] != (self.img_height, self.img_width):
            img_bgr = cv2.resize(img_bgr, (self.img_width, self.img_height))
        image_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

        # ── Load GT mask (loss target) and SEKO mask (box-prompt source) ──
        gt_mask = np.array(Image.open(rec["mask_path"])).astype(np.uint8)
        if gt_mask.shape[:2] != (self.img_height, self.img_width):
            gt_mask = cv2.resize(
                gt_mask, (self.img_width, self.img_height),
                interpolation=cv2.INTER_NEAREST
            )
        gt_mask = _merge_osteophyte_into_cartilage(gt_mask)

        seko_mask = np.array(Image.open(rec["seko_mask_path"])).astype(np.uint8)
        if seko_mask.shape[:2] != (self.img_height, self.img_width):
            seko_mask = cv2.resize(
                seko_mask, (self.img_width, self.img_height),
                interpolation=cv2.INTER_NEAREST
            )

        if self.augment:
            image_tensor, aug_gt, aug_seko = augment_triplet(image_rgb, gt_mask, seko_mask)
            boxes_list, masks_list, labels_list = _extract_prompted_instances(aug_seko, aug_gt)
            if not boxes_list:
                # Rare: a rotation/flip cropped out every class that
                # survived __init__'s pre-filter on the un-augmented SEKO
                # mask. Fall back to the deterministic view of this image.
                image_tensor = preprocess_image(image_rgb)
                boxes_list, masks_list, labels_list = _extract_prompted_instances(seko_mask, gt_mask)
        else:
            image_tensor = preprocess_image(image_rgb)
            boxes_list, masks_list, labels_list = _extract_prompted_instances(seko_mask, gt_mask)

        return {
            "image_rgb":    image_rgb,
            "image_tensor": image_tensor,
            "boxes_cxcywh": torch.tensor(boxes_list, dtype=torch.float32),
            "binary_masks": torch.from_numpy(np.stack(masks_list)),  # (N, H, W) bool
            "label_ids":    torch.tensor(labels_list, dtype=torch.long),
        }


# ── Prompt / target builders ───────────────────────────────────────────────

def build_prompt(boxes_cxcywh: torch.Tensor, device) -> Prompt:
    """
    Build a SAM 3 Prompt from N GT bounding boxes.

    Prompt expects:
        box_embeddings : (N, B, 4)  — N instances, B=1 image
        box_mask       : (B, N)     — True = valid
        box_labels     : (N, B)     — 1 = positive prompt
    """
    N = boxes_cxcywh.shape[0]
    boxes = boxes_cxcywh.to(device).unsqueeze(1)           # (N, 1, 4)
    box_mask   = torch.ones(1, N, device=device, dtype=torch.bool)
    box_labels = torch.ones(N, 1, device=device, dtype=torch.long)
    return Prompt(box_embeddings=boxes, box_mask=box_mask, box_labels=box_labels)


def build_find_input(device) -> FindStage:
    """Minimal FindStage with no input boxes (prompts passed via geometric_prompt)."""
    return FindStage(
        img_ids=torch.tensor([0], device=device, dtype=torch.long),
        text_ids=torch.tensor([0], device=device, dtype=torch.long),
        input_boxes=None,
        input_boxes_mask=None,
        input_boxes_label=None,
        input_points=None,
        input_points_mask=None,
    )


def build_find_target(
    boxes_cxcywh: torch.Tensor,
    binary_masks: torch.Tensor,
    device,
) -> BatchedFindTarget:
    """
    Build a BatchedFindTarget for one image with N tissue instances.

    boxes_cxcywh : (N, 4) normalized cxcywh
    binary_masks : (N, H, W) bool
    """
    N = boxes_cxcywh.shape[0]
    H, W = binary_masks.shape[1], binary_masks.shape[2]

    boxes    = boxes_cxcywh.to(device)           # (N, 4)
    segments = binary_masks.to(device)            # (N, H, W) bool

    # Semantic mask = union of all instance masks — (1, H, W)
    semantic = segments.any(dim=0, keepdim=True)  # (1, H, W)

    return BatchedFindTarget(
        num_boxes=torch.tensor([N], device=device, dtype=torch.long),
        boxes=boxes,
        boxes_padded=boxes.unsqueeze(0),          # (1, N, 4)
        repeated_boxes=boxes.repeat(2, 1),        # (2N, 4) — for DAC/hybrid matching
        segments=segments,
        semantic_segments=semantic,
        is_valid_segment=torch.ones(N, device=device, dtype=torch.bool),
        is_exhaustive=torch.ones(1, device=device, dtype=torch.bool),
        object_ids=torch.arange(N, device=device, dtype=torch.long),
        object_ids_padded=torch.arange(N, device=device, dtype=torch.long).unsqueeze(0),
    )


# ── Loss ───────────────────────────────────────────────────────────────────

def compute_loss_and_dice(
    out: dict, boxes_cxcywh: torch.Tensor, binary_masks: torch.Tensor, device,
    label_ids: list | None = None,
) -> tuple[torch.Tensor, float, dict]:
    """
    Compute Dice + BCE loss and DICE metrics on Hungarian-matched (pred, GT) pairs.

    Returns (loss, mean_dice, per_class_dice) where:
      mean_dice       : float — average DICE across matched pairs
      per_class_dice  : dict {label_id: dice} — only populated when label_ids is given

    out["pred_masks"] : (B, Q, H_pred, W_pred) — raw logits from model
    out["pred_boxes"] : (B, Q, 4) — predicted boxes in cxcywh normalized
    boxes_cxcywh      : (N, 4) GT boxes
    binary_masks      : (N, H_orig, W_orig) bool GT masks
    label_ids         : list of N ints mapping GT index → tissue class
    """
    pred_masks = out.get("pred_masks")   # (1, Q, H, W)
    pred_boxes = out.get("pred_boxes")   # (1, Q, 4)
    if pred_masks is None or pred_boxes is None:
        return torch.tensor(0.0, device=device, requires_grad=True), 0.0, {}

    gt_boxes = boxes_cxcywh.to(device)       # (N, 4)
    pred_b   = pred_boxes[0].detach()         # (Q, 4)

    # L1 cost between each GT box and each predicted query → (N, Q)
    cost = torch.cdist(gt_boxes, pred_b, p=1).cpu().numpy()

    # Hungarian: assign each GT to the best predicted query
    gt_idx, pred_idx = linear_sum_assignment(cost)   # both shape (M,)

    if len(pred_idx) == 0:
        return torch.tensor(0.0, device=device, requires_grad=True), 0.0, {}

    matched_preds = pred_masks[0, pred_idx]                       # (M, H_pred, W_pred)
    matched_gt    = binary_masks[gt_idx].to(device).float()       # (M, H_orig, W_orig)

    H_pred, W_pred = matched_preds.shape[-2], matched_preds.shape[-1]

    # Resize GT to match prediction resolution
    matched_gt = F.interpolate(
        matched_gt.unsqueeze(1),
        size=(H_pred, W_pred),
        mode="nearest",
    ).squeeze(1)   # (M, H_pred, W_pred)

    M = matched_preds.shape[0]

    loss_bce  = F.binary_cross_entropy_with_logits(
        matched_preds.flatten(1),
        matched_gt.flatten(1),
        reduction="mean",
    )
    loss_dice = dice_loss(
        matched_preds.flatten(1),
        matched_gt.flatten(1),
        num_boxes=torch.tensor(M, device=device, dtype=torch.float32),
    )

    # DICE metric: threshold predictions at 0.5, no gradient needed
    with torch.no_grad():
        pred_bin  = (matched_preds.sigmoid() > 0.5).float()
        inter     = (pred_bin * matched_gt).sum(dim=(-2, -1))
        union     = pred_bin.sum(dim=(-2, -1)) + matched_gt.sum(dim=(-2, -1))
        dice_vals = (2.0 * inter + 1e-6) / (union + 1e-6)
        mean_dice = dice_vals.mean().item()
        per_class = (
            {label_ids[gt_idx[i]]: dice_vals[i].item() for i in range(len(gt_idx))}
            if label_ids is not None else {}
        )

    return loss_bce + loss_dice, mean_dice, per_class


# ── Training / validation steps ────────────────────────────────────────────

def run_epoch(model, loader, optimizer, device, train: bool) -> dict:
    """
    Returns {"loss": float, "dice": float, "class_dice": {label_id: float}}.
    class_dice is accumulated for every step (train and val).
    """
    model.train(train)
    context = torch.enable_grad if train else torch.no_grad
    # SAM3 is designed to run under bfloat16 autocast on CUDA
    autocast_ctx = (
        torch.autocast(device_type="cuda", dtype=torch.bfloat16)
        if device.type == "cuda"
        else contextlib.nullcontext()
    )
    total_loss, total_dice, n = 0.0, 0.0, 0
    class_sums   = {k: 0.0 for k in TISSUE_LABELS}
    class_counts = {k: 0   for k in TISSUE_LABELS}

    with context():
        for batch in loader:
            image_tensor  = batch["image_tensor"].squeeze(0).to(device)  # (1, 3, H, W)
            boxes_cxcywh  = batch["boxes_cxcywh"].squeeze(0)             # (N, 4)
            binary_masks  = batch["binary_masks"].squeeze(0)             # (N, H, W)
            label_ids     = batch["label_ids"].squeeze(0).tolist()       # [int, ...]

            with autocast_ctx:
                # ── Backbone forward (frozen — no grad) ──────────────────
                with torch.no_grad():
                    backbone_out = model.backbone.forward_image(image_tensor)
                    text_out     = model.backbone.forward_text(["visual"], device=device)
                    backbone_out.update(text_out)

                # ── Build prompts + target ───────────────────────────────
                prompt      = build_prompt(boxes_cxcywh, device)
                find_input  = build_find_input(device)
                find_target = build_find_target(boxes_cxcywh, binary_masks, device)

                # ── Forward through trainable components ─────────────────
                out = model.forward_grounding(
                    backbone_out=backbone_out,
                    find_input=find_input,
                    find_target=find_target,
                    geometric_prompt=prompt,
                )

            loss, dice, per_class = compute_loss_and_dice(
                out, boxes_cxcywh, binary_masks, device, label_ids=label_ids
            )

            if train and loss.requires_grad:
                optimizer.zero_grad()
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

            total_loss += loss.item()
            total_dice += dice
            for cls_id, d in per_class.items():
                if cls_id in class_sums:
                    class_sums[cls_id]   += d
                    class_counts[cls_id] += 1
            n += 1

    class_dice = {
        k: class_sums[k] / class_counts[k]
        for k in TISSUE_LABELS if class_counts[k] > 0
    }
    return {"loss": total_loss / max(n, 1), "dice": total_dice / max(n, 1),
            "class_dice": class_dice}


# ── Freezing ────────────────────────────────────────────────────────────────

def freeze_backbone(model):
    """Freeze the ViT image encoder — the most expensive component."""
    frozen, total = 0, 0
    for name, param in model.named_parameters():
        total += 1
        if "backbone.vision_backbone.trunk" in name:
            param.requires_grad_(False)
            frozen += 1
    if frozen == 0:
        raise RuntimeError(
            f"freeze_backbone matched 0/{total} parameters against "
            "'backbone.vision_backbone.trunk' — the SAM 3 model's parameter "
            "naming doesn't match this pattern. Refusing to silently "
            "finetune the full backbone; update the match string."
        )
    print(f"Froze {frozen}/{total} parameters (ViT backbone)")


# ── Main ────────────────────────────────────────────────────────────────────

def main():
    with open(CONFIG_PATH) as f:
        cfg = yaml.safe_load(f)

    parser = argparse.ArgumentParser(description="Finetune SAM 3 on TOAD histology data")
    parser.add_argument("--ckpt",       default=cfg["sam3"].get("ckpt_path", None),
                        help="SAM 3 checkpoint path (downloads from HF if omitted)")
    parser.add_argument("--csv",        default=cfg["paths"]["train_seko_csv"],
                        help="Path to train_seko.csv (image_path, mask_path, "
                             "seko_mask_path, stain) — generated by "
                             "src/utils/cache_seko_masks.py")
    parser.add_argument("--output-dir", default=cfg["paths"]["output_dir"],
                        help="Directory for saved checkpoints")
    parser.add_argument("--device",     default=cfg["sam3"].get("device", "cuda"),
                        help="'cuda', 'mps', or 'cpu'")
    parser.add_argument("--epochs",     type=int,   default=20)
    parser.add_argument("--lr",         type=float, default=1e-4)
    parser.add_argument("--val-frac",   type=float, default=0.15,
                        help="Fraction of data held out for validation")
    parser.add_argument("--seed",       type=int,   default=42)
    args = parser.parse_args()

    # ── Device ──────────────────────────────────────────────────────────
    if args.device == "cuda" and not torch.cuda.is_available():
        print("CUDA not available — falling back to CPU")
        args.device = "cpu"
    device = torch.device(args.device)
    print(f"Device: {device}")

    # ── Data ────────────────────────────────────────────────────────────
    df = pd.read_csv(args.csv)
    records = df.to_dict("records")
    train_recs, val_recs = train_test_split(
        records, test_size=args.val_frac, random_state=args.seed
    )
    print(f"Train: {len(train_recs)}  Val: {len(val_recs)}")

    img_h = cfg["data"]["img_height"]
    img_w = cfg["data"]["img_width"]

    train_ds = ToadSam3Dataset(train_recs, img_h, img_w, augment=True)
    val_ds   = ToadSam3Dataset(val_recs,   img_h, img_w, augment=False)
    print(f"ToadSam3Dataset after SEKO-detection filter — train: {len(train_ds)}  val: {len(val_ds)}")

    # DataLoader with batch_size=1 — SAM 3 processes one image at a time
    train_loader = DataLoader(train_ds, batch_size=1, shuffle=True,  num_workers=2)
    val_loader   = DataLoader(val_ds,   batch_size=1, shuffle=False, num_workers=2)

    # ── Model ───────────────────────────────────────────────────────────
    load_from_hf = (args.ckpt is None) or (not os.path.isfile(args.ckpt))
    print(f"Loading SAM 3 model (checkpoint: {'HuggingFace' if load_from_hf else args.ckpt})")
    model = build_sam3_image_model(
        checkpoint_path=args.ckpt if not load_from_hf else None,
        load_from_HF=load_from_hf,
        device=str(device),
        eval_mode=False,
    )

    freeze_backbone(model)

    # ── Optimizer ───────────────────────────────────────────────────────
    trainable = [p for p in model.parameters() if p.requires_grad]
    print(f"Trainable parameter tensors: {len(trainable)}")
    optimizer = torch.optim.AdamW(trainable, lr=args.lr, weight_decay=1e-4)

    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs, eta_min=args.lr * 0.1
    )

    # ── Training loop ────────────────────────────────────────────────────
    ckpt_dir = os.path.join(args.output_dir, "sam3_checkpoints")
    os.makedirs(ckpt_dir, exist_ok=True)

    best_val_loss = float("inf")
    best_val_dice = 0.0
    best_ckpt_path = os.path.join(ckpt_dir, "sam3_toad_best.pt")

    metrics_log = {"epoch": [], "train_loss": [], "val_loss": [],
                   "train_dice": [], "val_dice": [], "val_class_dice": []}
    metrics_path = os.path.join(args.output_dir, "metrics.json")

    print(f"\n{'Epoch':>5}  {'TrainLoss':>9}  {'ValLoss':>8}  "
          f"{'TrainDICE':>9}  {'ValDICE':>8}  {'LR':>8}  {'Time':>6}")
    print("-" * 68)

    for epoch in range(1, args.epochs + 1):
        t0 = time.time()

        train_stats = run_epoch(model, train_loader, optimizer, device, train=True)
        val_stats   = run_epoch(model, val_loader,   optimizer, device, train=False)

        scheduler.step()

        elapsed = time.time() - t0
        marker = " ★" if val_stats["dice"] > best_val_dice else ""

        print(
            f"{epoch:5d}  "
            f"{train_stats['loss']:9.4f}  {val_stats['loss']:8.4f}  "
            f"{train_stats['dice']:9.4f}  {val_stats['dice']:8.4f}  "
            f"{scheduler.get_last_lr()[0]:.2e}  {elapsed:5.0f}s"
            f"{marker}",
            flush=True,
        )

        # Per-class val DICE on a second line
        class_parts = "  ".join(
            f"{TISSUE_NAMES[k]}:{val_stats['class_dice'][k]:.3f}"
            for k in TISSUE_LABELS if k in val_stats["class_dice"]
        )
        if class_parts:
            print(f"       val/class — {class_parts}", flush=True)

        # Update metrics log and persist after every epoch
        metrics_log["epoch"].append(epoch)
        metrics_log["train_loss"].append(round(train_stats["loss"], 6))
        metrics_log["val_loss"].append(round(val_stats["loss"], 6))
        metrics_log["train_dice"].append(round(train_stats["dice"], 6))
        metrics_log["val_dice"].append(round(val_stats["dice"], 6))
        metrics_log["val_class_dice"].append(
            {str(k): round(v, 6) for k, v in val_stats["class_dice"].items()}
        )
        with open(metrics_path, "w") as f:
            json.dump(metrics_log, f, indent=2)

        if val_stats["loss"] < best_val_loss:
            best_val_loss = val_stats["loss"]
        if val_stats["dice"] > best_val_dice:
            best_val_dice = val_stats["dice"]
            torch.save(
                {"epoch": epoch, "model_state_dict": model.state_dict(),
                 "val_loss": val_stats["loss"], "val_dice": val_stats["dice"]},
                best_ckpt_path,
            )

    # Always save the final epoch too
    final_ckpt = os.path.join(ckpt_dir, f"sam3_toad_epoch{args.epochs}.pt")
    torch.save(
        {"epoch": args.epochs, "model_state_dict": model.state_dict(),
         "val_loss": val_stats["loss"], "val_dice": val_stats["dice"]},
        final_ckpt,
    )
    print(f"\nDone. Best val DICE: {best_val_dice:.4f}  Best val loss: {best_val_loss:.4f}")
    print(f"Metrics saved → {metrics_path}")
    print(f"Best checkpoint → {best_ckpt_path}")


if __name__ == "__main__":
    main()
